### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mieradi** [ol-th/pdf-img-convert.js#63]
`Node v20`
`pnpm v9.12.2`

I cannot use v2 of this package due to commonjs not being supported at all anymore. Is there a way we can get support for both esm and commonjs? 

Thanks for the great work!

**Comment by wariomvc** [comment]
Same problem, using NestJS
the previous version (v1.2) worked fine

**Comment by zhiweit** [comment]
Fix: Update the config file.

You might have to make some changes to your vite config file if you are using vite.
In my case, fixed it by adding this to the `app.config.ts` file
```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  vite: {
    ssr: {
      noExternal: ["pdf-img-convert", "node-fetch"],
    },
  },
});

```

I also experienced this error in my project using solidjs. 
```ts
Cannot use import statement outside a module

/.../node_modules/.pnpm/pdf-img-convert@2.0.0_encoding@0.1.13/node_modules/pdf-img-convert/pdf-img-convert.js:1
import fetch from 'node-fetch';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async nodeImport 
```

Answer reference from gpt 4-o

> Adjust Vite Configuration
Vite needs to know how to handle certain dependencies during the build process. You can adjust the vite.config.ts file to ensure that pdf-img-convert is treated correctly.
vite.config.ts
Explanation:
The ssr.noExternal option tells Vite to bundle pdf-img-convert and node-fetch instead of treating them as external dependencies. This is crucial for libraries that use ES Module syntax.

**Comment by JCMais** [comment]
The error here is actually that this package is not setting itself as a esmodule in the package.json

The author needs to set `"type": "module"` in the `package.json`.

**Comment by gcalabria** [comment]
Setting `"type": "module"` in the `package.json` solved the bug above but now I am getting:
```bash
Failed parsing file into parts TypeError: process.getBuiltinModule is not a function
```
Any ideas?

**Comment by anthony-bendeler-io** [comment]
"The author needs to set "type": "module" in the package.json."


changing the config then gives the following error: 

Object.defineProperty(exports, "__esModule", { value: true });
                      ^
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/anthonybendeler/Documents/projects/file-compression/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

**Comment by anthony-bendeler-io** [comment]
"The author needs to set "type": "module" in the package.json."

changing the config then gives the following error:

Object.defineProperty(exports, "__esModule", { value: true });
^
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'file-compression/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

**Comment by acostablueday** [comment]
I have the same problem, any news to resolve it?

**Comment by Muktar16** [comment]
I am also experiencing this issue in my playwright testing app. I have added "type": "module" into my package.json file. But still this error is arising. 

`(node:46071) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Error converting or cropping images: /home/bs997/Desktop/mif-automation/node_modules/pdf-img-convert/pdf-img-convert.js:1
import fetch from 'node-fetch';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.i.<computed>.ut._extensions.<computed> [as .js] (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/utilsBundleImpl.js:16:1010)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at RuntimeReportComponent.convertPdfToImages (file:///home/bs997/Desktop/mif-automation/src/pages/email-content-verification/runtime-report.component.ts:23:23)
    at file:///home/bs997/Desktop/mif-automation/src/tests/email-content-verification/runtime-report-pdf.spec.ts:61:3
    at /home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/workerMain.js:341:9
    at /home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/testInfo.js:294:11
    at TimeoutManager.withRunnable (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/timeoutManager.js:64:14)
    at TestInfoImpl._runAsStage (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/testInfo.js:292:7)
    at /home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/workerMain.js:333:7
    at /home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/testInfo.js:294:11
    at TimeoutManager.withRunnable (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/timeoutManager.js:52:27)
    at TestInfoImpl._runAsStage (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/testInfo.js:292:7)
    at WorkerMain._runTest (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/workerMain.js:283:5)
    at WorkerMain.runTestGroup (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/worker/workerMain.js:207:11)
    at process.<anonymous> (/home/bs997/Desktop/mif-automation/node_modules/playwright/lib/common/process.js:95:22)`
